### ISSUE TITLE
Crash when operating the Locked Windows feature in SimpleTweaks

### ISSUE THREAD

**Issue by torakiti2017** [Aireil/FFLogsViewer#36] opened 2023-11-23 08:34 UTC
When operating the Locked Windows feature of SimpleTweaks with FFLogsViewer enabled, a crash occurs.
If I disable FFLogsViewer, I can operate the Locked Windows function without crashing.

Operation procedure
1. Right-click in the character menu (open context menu).
2.Click on ST Window Position Locked
3. the game crashes.

**Comment by Aireil** [comment] 2023-11-23 09:44
I'm going to check, but that sounds weird, was it working before? There were no change to the tweak in 4 months and the only thing that interacts with context menus in FFLogsViewer has had no change in the last 6 months.

**Comment by Aireil** [comment] 2023-11-23 12:38
As expected, I cannot reproduce the issue, the window locks and there is no crash.
Could you try:
1. Close the game
2. Rename the directory `%appdata%/XIVLauncher/installedPlugins`
3. Start the game
4. Install only SimpleTweaks and FFLogsViewer
5. Is it still crashing?

You can rename the directory back to the proper name once you've closed your game again to restore all your plugins.

**Comment by torakiti2017** [comment] 2023-11-24 11:59
With only SimpleTweaks and FFLogsViewer installed, no crashes occurred.
Thank you for the information on how to check this.
We are sorry to have taken so much of your time.

**Comment by Aireil** [comment] 2023-11-24 12:07
No worries, I would still be interested to know which combination of plugins is causing this.
You can try to identify it yourself by enabling only half of your plugins at a time or just send me your installed plugins.
To get an easy list of your installed plugins, you can open a command prompt (cmd) and use the command: `dir /b "%appdata%/XIVLauncher/installedPlugins"`
Thanks!

**Comment by torakiti2017** [comment] 2023-11-24 17:12
We tried to find out the combination but could not because the behaviour did not match.
If you enable them one by one, it may not crash even with all of them enabled, or it may crash after a number of plugins, etc.
Sometimes it was fine, but not when I restarted, and I couldn't identify it. Sorry.

A list of installed plugins is attached.
[plugin.txt](https://github.com/Aireil/FFLogsViewer/files/13461254/plugin.txt)

**Comment by Aireil** [comment] 2023-11-24 17:23
Thank you, I'm going to check if I can reproduce it. At least I know the crash exists.
Just to be sure, when you say the game crashes, does the game window just disappear or do you see a window like this?

![image](https://cdn.discordapp.com/attachments/1084906540592549958/1176380150028439562/image.png?ex=656ea863&is=655c3363&hm=12cea5a4df4463a19fd82a6e924a9e3c3188c523203cdd7385db9bc5d891831c&)

**Comment by torakiti2017** [comment] 2023-11-24 17:56
I have now tried four times, and only the first time an error screen appeared. On the subsequent three occasions, the game window just disappeared.
<img width="442" alt="無題" src="https://github.com/Aireil/FFLogsViewer/assets/86459831/d815a817-8ef8-4cf8-8942-9f688fc43f9a">

**Comment by Aireil** [comment] 2023-11-24 18:06
Could you please send me these two files that are in `%appdata%/XIVLauncher`:
- `dalamud_appcrash[...].log`, send the most recent
- `dalamud.log`

These will contain your Windows user name, if you care about not sharing it in public, either replace it before uploading or contact me on Discord: Aireil

Thank you again~

**Comment by Aireil** [comment] 2023-11-24 19:16
As mentioned in DMs, it seems like it's indeed from SimpleTweaks' tweak, closing this issue as it's no longer related to FFLogsViewer.

Thank you for the report!

**Closed by Aireil** 2023-11-24 19:16 UTC
