### ISSUE TITLE
Doesn’t show endwalker ultimate parses

### ISSUE THREAD

**Issue by wolfjake-uoft** [Aireil/FFLogsViewer#7] opened 2022-02-02 15:51 UTC
title + shows shadowbringers currently

**Comment by Aireil** [comment] 2022-02-03 01:21
Indeed, the problem is that FFLogs splits them all by expansion. Getting all that info would cost too many points and things like medians would be impossible to compute.
After talking with the devs, they're planning to have an aggregated endpoint soon, so I'm going to wait on that before changing how it's currently working.
Thank you for the report, I didn't even know it was only getting EW ultimates.

**Comment by Aireil** [comment] 2022-03-22 16:41
Swap EW <=> ShB available in 1.5.6.2; thanks Variosss for #10 .
Still waiting on the aggregated endpoint from FFLogs, but that's a good temporary patch.

**Comment by Aireil** [comment] 2022-04-19 13:54
2.0.0.0 adds a customizable layout, you can add any encounter you want in the settings.
This drops the swapping support for now, I will maybe think of a way to allow this in a future version.

I'm closing this for now, as this is mainly on FF Logs.

**Closed by Aireil** 2022-04-19 13:54 UTC
