### ISSUE TITLE
Feature: Progression visibility

### ISSUE THREAD

**Issue by Gasteno** [Aireil/FFLogsViewer#41] opened 2024-05-03 00:57 UTC
Thanks for a great plugin. A feature request, would be great to add Extreme, Savage, and Ultimate content progression info similar to how https://tomestone.gg/ does it.
Thanks!!

**Comment by Aireil** [comment] 2024-05-03 09:54
Duplicate of #37 with the same conclusion for now. I'm keeping an eye out if anything changes.

**Closed by Aireil** 2024-05-03 09:54 UTC
