### ISSUE TITLE
Moving tables, again

### ISSUE THREAD

**Issue by Tischel** [Aireil/FFLogsViewer#40] opened 2024-04-20 17:49 UTC
This time its the Layout tab.

https://i.gyazo.com/76cdf5e91d60ffcae91c8c7f1e332860.gif

**Comment by Aireil** [comment] 2024-04-20 18:10
Pfff, of course you did this again!
Your global scale isn't default right?

**Comment by Tischel** [comment] 2024-04-20 18:12
![image](https://github.com/Aireil/FFLogsViewer/assets/6404136/32891800-992c-41c2-80bb-52892b39c894)

**Comment by Aireil** [comment] 2024-04-20 18:14
Yeah OK nice, same issue as last time then, I'll fix it for the next update, thanks!

**Comment by Aireil** [comment] 2024-04-23 18:11
Hmm, looking at it now, I don't even use the global scale directly in there, so it's probably not the same issue.
But I can't reproduce it, so it'll probably stay like this because I don't really care that much about that happening in settings 💀.
You're not using a special theme right?

**Comment by Aireil** [comment] 2024-07-21 08:23
After MONTHS of research, I've finally landed on a sound (🤡) strategy:
Rounding everything!!
2.1.7.2 _should_ hopefully fix this issue for good (I will cry if you get it again).

**Comment by Aireil** [comment] 2024-07-27 06:59
Closing the issue because it of course works and I'm the best at fixing bugs. Surely this will never happen again!! 🎪

**Closed by Aireil** 2024-07-27 06:59 UTC
